# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from uninstall import *


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icons/256x256.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Home.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=Home)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(parent=self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 30, 801, 81))
        self.title.setObjectName("title")
        self.pushButton_install = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_install.setGeometry(QtCore.QRect(50, 170, 170, 70))
        self.pushButton_install.setObjectName("pushButton_install")
        self.pushButton_uninstall = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_uninstall.setGeometry(QtCore.QRect(310, 170, 171, 71))
        self.pushButton_uninstall.setObjectName("pushButton_uninstall")
        self.pushButton_uninstall.clicked.connect(self.C_Uninstall)
        self.pushButton_run_flatpak = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_run_flatpak.setGeometry(QtCore.QRect(570, 170, 171, 71))
        self.pushButton_run_flatpak.setObjectName("pushButton_run_flatpak")
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(310, 340, 171, 71))
        self.pushButton_exit.setObjectName("pushButton_exit")
        Home.setCentralWidget(self.centralwidget)

        self.retranslateUi(Home)
        self.pushButton_exit.pressed.connect(Home.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Home)

        self.home_window = Home  # 保存主窗口引用

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "yay+ PyQt Version(Beta)"))
        self.title.setText(_translate("Home", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:700;\">yay+ PyQt版（测试中）</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:700;\">版本0.1 Beta</span></p></body></html>"))
        self.pushButton_install.setText(_translate("Home", "安装"))
        self.pushButton_uninstall.setText(_translate("Home", "卸载"))
        self.pushButton_run_flatpak.setText(_translate("Home", "运行（Flatpak软件包）"))
        self.pushButton_exit.setText(_translate("Home", "退出"))

    # C_Uninstall和restore_main_window由Deepseek-r1生成
    def C_Uninstall(self):
        # 方法一：使用模态对话框（推荐）
        self.uninstall_dialog = QtWidgets.QDialog()
        self.ui_uninstall = Ui_Uninstall()
        self.ui_uninstall.setupUi(self.uninstall_dialog)

        # 设置关闭时自动销毁
        self.uninstall_dialog.setAttribute(QtCore.Qt.WidgetAttribute.WA_DeleteOnClose)

        # 连接对话框关闭信号
        self.uninstall_dialog.finished.connect(self.restore_main_window)

        # 设置为模态
        self.uninstall_dialog.exec()

    def restore_main_window(self, result):
        print("卸载窗口已关闭，返回码:", result)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QMainWindow()
    ui = Ui_Home()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec())
