# Form implementation generated from reading ui file 'uninstall_pacman.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os


class Ui_Uninstall_Pacman(object):
    def setupUi(self, Uninstall_Pacman):
        Uninstall_Pacman.setObjectName("Uninstall_Pacman")
        Uninstall_Pacman.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/256x256.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Uninstall_Pacman.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(parent=Uninstall_Pacman)
        self.label.setGeometry(QtCore.QRect(98, 40, 601, 91))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=Uninstall_Pacman)
        self.lineEdit.setGeometry(QtCore.QRect(92, 180, 611, 27))
        self.lineEdit.setObjectName("lineEdit")
        self.input_text = ""
        self.pushButton_no = QtWidgets.QPushButton(parent=Uninstall_Pacman)
        self.pushButton_no.setGeometry(QtCore.QRect(440, 510, 111, 41))
        self.pushButton_no.setObjectName("pushButton_no")
        self.pushButton_no.clicked.connect(Uninstall_Pacman.reject)
        self.pushButton_yes = QtWidgets.QPushButton(parent=Uninstall_Pacman)
        self.pushButton_yes.setGeometry(QtCore.QRect(590, 510, 111, 41))
        self.pushButton_yes.setObjectName("pushButton_yes")
        self.pushButton_yes.clicked.connect(self.yes_button_clicked)

        self.retranslateUi(Uninstall_Pacman)
        QtCore.QMetaObject.connectSlotsByName(Uninstall_Pacman)

    def retranslateUi(self, Uninstall_Pacman):
        _translate = QtCore.QCoreApplication.translate
        Uninstall_Pacman.setWindowTitle(_translate("Uninstall_Pacman", "Dialog"))
        self.label.setText(_translate("Uninstall_Pacman", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:700;\">卸载</span></p></body></html>"))
        self.lineEdit.setText(_translate("Uninstall_Pacman", "修改此处文字修改为你要卸载的软件名称（支持多个，用空格隔开）"))
        self.pushButton_no.setText(_translate("Uninstall_Pacman", "取消"))
        self.pushButton_yes.setText(_translate("Uninstall_Pacman", "确定"))

    def yes_button_clicked(self):
        self.input_text = self.lineEdit.text()
        os.system("sudo --askpass askpass.sh pacman -Rsn {self.input_text}")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Uninstall_Pacman = QtWidgets.QDialog()
    ui = Ui_Uninstall_Pacman()
    ui.setupUi(Uninstall_Pacman)
    Uninstall_Pacman.show()
    sys.exit(app.exec())
